/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sqr.h"


void
sqr_prog_1(char *host, int a)
{
	CLIENT *clnt;
	int  *result_1;
	number  sqr_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SQR_PROG, SQR_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	sqr_1_arg.a = a;
	result_1 = sqr_1(&sqr_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Server responsded with %d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host NUMBER\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	sqr_prog_1 (host, atoi(argv[2]));
exit (0);
}
